### ISSUE TITLE
Install process json file creation

### ISSUE THREAD

**Issue by DivisionVapor** [ShoppinPal/vend-tools#20]
Going through the video and chat logs that Pulkit made for me and I'm not seeing the example json file on the site anymore.  I think I managed to recreate it anyway and the oauth file, but when I try the next step, npm install, it says npm is not recognized as a command.

**Comment by pulkitsinghal** [comment]
@DivisionVapor - can we jump into a screenshare?

**Comment by pulkitsinghal** [comment]
Also any messages sent via https://gitter.im/ShoppinPal/vend-tools show up in my mobile notification window, so you can reach out to me quicker that way too.

**Comment by pulkitsinghal** [comment]
@DivisionVapor - Glad we worked that out, here's a reference to the patch for posterity: https://github.com/ShoppinPal/vend-tools/commit/1048ca337cb4f8804bf191b171f8415998219a84

We were losing product id because sorting changed a map to an array.
