### ISSUE TITLE
Over-large orders

### ISSUE THREAD

**Issue by DivisionVapor** [ShoppinPal/vend-tools#21]
Pulkit,

  I've run one of my vendors now three times today and it looks like it's pulling from the entire stock history as if it's hitting that one server that you mentioned with the bad code.  But three times?  That's pretty unlikely three times in a row.  Need a sanity check.

**Comment by pulkitsinghal** [comment]
I'll get on it

**Comment by DivisionVapor** [comment]
Just got back from lunch.  If you want to see the results, I can show you.

**Comment by DivisionVapor** [comment]
not sure I have your number
