### ISSUE TITLE
Remove the "short" suffix from generated reports

### ISSUE THREAD

**Issue by pulkitsinghal** [ShoppinPal/vend-tools#24]
@DivisionVapor wants this done

**Comment by pulkitsinghal** [comment]
@MeghaY - There is a flag that lets us know to skip the `*-long` order name creation ... so if that happens then whereever a report with  `*-short` order name is about to be created ... it should respect the fact that there isn't a `blahBlah-long` report so there is no need to distinguish the `blahBlah-short` report with the suffix either ... just use a condition and leave the order name as `blahBlah`

**Comment by MeghaY** [comment]
@pulkitsinghal - Is this the flag you are talking about? https://github.com/ShoppinPal/vend-tools/blob/master/commands/generate-stock-order.js#L603

**Comment by pulkitsinghal** [comment]
Yup!

**Comment by pulkitsinghal** [comment]
@MeghaY - thanks for finishing up https://github.com/ShoppinPal/vend-tools/pull/28 ... I'll close out this issue now.
