### ISSUE TITLE
Vend-tools not recognized as command...

### ISSUE THREAD

**Issue by DivisionVapor** [ShoppinPal/vend-tools#29]
Vend-tools is not recognized as an internal or external command
, operable program or batch file.

Getting either this, or it's not running at all today.  On multiple computers.

**Comment by pulkitsinghal** [comment]
@DivisionVapor - we should schedule something soon, i don't know what this is so I would need to do a screenshare with you. Let me know when?

**Comment by DivisionVapor** [comment]
Do you want to take a quick look now?  We'd have to talk by phone, but I
could screen share.  I don't have my headset with me.

On Fri, Jun 19, 2015 at 8:11 PM, Pulkit Singhal notifications@github.com
wrote:

> @DivisionVapor https://github.com/DivisionVapor - we should schedule
> something soon, i don't know what this is so I would need to do a
> screenshare with you. Let me know when
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ShoppinPal/vend-tools/issues/29#issuecomment-113701345
> .

## 

Regards,

Division Vapor
2929 SE Powell Blvd.
Portland, OR 97202
503-963-8273

1207 NE Alberta St.
Portland, OR 97211
503-281-8273

**Comment by pulkitsinghal** [comment]
Sure I called but I got your store line.

- Pulkit
(646)-535-2357

**Comment by DivisionVapor** [comment]
cell number 360-608-8780


On Fri, Jun 19, 2015 at 8:15 PM, Pulkit Singhal <notifications@github.com>
wrote:

> Sure I called but I got your store line.
>
> - Pulkit
> (646)-535-2357
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShoppinPal/vend-tools/issues/29#issuecomment-113701831>
> .
>



-- 
Regards,

Division Vapor
2929 SE Powell Blvd.
Portland, OR 97202
503-963-8273

1207 NE Alberta St.
Portland, OR 97211
503-281-8273

**Comment by pulkitsinghal** [comment]
Glad we resolved it, I'll look into why an auto-update via the underlying Ronin module might deregister an existing module like vend-tools on windows from the global registry
