### ISSUE TITLE
path for export file

### ISSUE THREAD

**Issue by elbrando** [ShoppinPal/vend-tools#3]
Would be nice to specify once where the file should be saved rather than it being dropped in the working folder.

**Comment by pulkitsinghal** [comment]
... and the filename too for sure.

**Comment by elbrando** [comment]
File name, too, please.

**Comment by pulkitsinghal** [comment]
Ok I will add and `--output` option and just to make things a bit easier, also add an `-o` alias for shorthand. Leaving a dev reference for myself or whomever else wants to finish this feature before me: http://vdemedes.github.io/ronin/guides/options/

**Comment by pulkitsinghal** [comment]
Introducing a new `settings.json` file:

```
{
  "defaultOutputDirectory": "/Users/pulkitsinghal/Dropbox/vend-tools",
  "timestampFiles": false
}
```

With such a config ... running:
`$ vend-tools fetch-product-by-sku --sku 100`

Throws the data into:
`/Users/pulkitsinghal/Dropbox/vend-tools/fetch-product-by-sku.json`
which is a predictable filename in a shared directory ... I wonder if that's good enough or if a custom output filename is still a worthy add-on?

**Comment by pulkitsinghal** [comment]
@elbrando reported that files with `*.csv` extensions don't follow the rules like the `*.json` ones! will fix soon
